### ISSUE TITLE
the spammer doesnt actually spam all the bots just send 1 message

### ISSUE THREAD

**Issue by minato-1** [Zenoryne/DiscSpam#19]
they dont spam

**Comment by Zenoryne** [comment]
What do you mean? 

 

I know discord has altered their API a little bit and I will be updating the tool when I have a little freer time. From my testing (this week) everything still works fine and all the functions in the tool work, maybe discord is blocking you IP addresses from their service if you’re using lots of tokens.

 

Have you tried to use the proxy mode in the tool or used a VPN?

 

From: minato-1 ***@***.***> 
Sent: Friday, January 21, 2022 11:22 AM
To: Zenoryne/DiscSpam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zenoryne/DiscSpam] the spammer doesnt actually spam all the bots just send 1 message (Issue #19)

 

they dont spam

**Comment by minato-1** [comment]
i used the spam message tool and it works but like they dont spam they only send 1 message each i said " test lol" and it only sent it once in chat

**Comment by Zenoryne** [comment]
You mean like an indefinite spam?

I have made the tokens only send one message each so they you can then keep running it as if I made them keep sending messages forever then discord would terminate the tokens fast. This is the main reason that people’s tokens get terminated. Think of it this way, when you use the discord client then they can show a pop up saying you are sending messages too fast. When you use their API there is no popup, so they just ban the token.

This is a little inconvenient I know but I wanted to make that token not getting banned was a priority. I will be adding this feature to keep spamming messages on a loop in the future but for right now just keep running the spam message action on the tool. : )
