### ISSUE TITLE
Joint Server

### ISSUE THREAD

**Issue by satoshinamamoto** [Zenoryne/DiscSpam#21]
Hello,

I have a question about the joint server.

All disco servers have verification in order to skip bots. If you use the tool, how do you bypass the verification in order to join? I don't see the option to add a captcha resolver api or similar.

Another question is if in your roadmap is expected to add the option to send Massive DM and Scraping Users of Server. 

About scraping, I think is a good idea to apply filters like:
-Filter for the default avatar
-Filter last 1 week new members discord join
-Scrap user roles in order to filter Admins and more. 

Let me know I'm happy to send all ideas in order to develop.

**Comment by HydraWard** [comment]
> 

did u update this yet?
