### ISSUE TITLE
Valid Token, unable to join a server.

### ISSUE THREAD

**Issue by Ownyd** [Zenoryne/DiscSpam#25]
Hey
Congrats for the work you've done here.
I defo need a tool like this

I encountered this blocking issue on my first test:
![image](https://user-images.githubusercontent.com/33722819/172614711-60e499fb-a442-4f85-a9ad-3631f912f9e1.png)

Also, do you have a tool you use to generate batch of discord tokens?
Thank you.

**Comment by Zenoryne** [comment]
This tool is outdated. I have no real desire to update it but it is on the list to do so.

Your token you have entered has been captcha flagged. This means if you try to join a guild then discord wants you do to a captcha when I update it I will automate that process but for now either use a non flagged token or a different IP address.

**Comment by Ownyd** [comment]
Thank you for your fast answer @Zenoryne 
Your tool looks good and have excellent catalysts, I hope you will update it!

Do you know how to get non flagged tokens & Make sure they are?
