### ISSUE TITLE
401 Unauthorized response, "Unable to Join" a server

### ISSUE THREAD

**Issue by gameveloster** [Zenoryne/DiscSpam#26]
Hi @Zenoryne, thank you for doing this in Golang!

When using the "Join Server" function, I am getting the error

``` 
<token> | Unable to Join <inviteCode>
```

Looked into the response returned `res` and its a `401 Unauthorized`. Getting the same error when I tried with more tokens and different proxy servers (and without proxy servers). All the accounts of these tokens have been created manually.

Any idea what might be the issue here? Thank you!

**Comment by Zenoryne** [comment]
Sounds like your tokens are not valid. Unauthorized is the response that comes back when you are trying to join on locked tokens. Try run the checker module in the tool and it will tell you what is wrong with the tokens.
