### ISSUE TITLE
Joining issue

### ISSUE THREAD

**Issue by golangman** [Zenoryne/DiscSpam#34]
![Снимок экрана 2023-02-01 в 00 40 00](https://user-images.githubusercontent.com/69013901/215889567-ee7ab0d1-69e0-4af3-89e7-2c67bbd7b422.png)

I get errors when trying to connect to any server (tried 5 different servers)
I also found out what error discord returns:
`"{\"message\": \"Unknown Message\", \"code\": 10008}"`

**Comment by golangman** [comment]
:(

**Comment by DerBruderHD** [comment]
pretty sure the project is dead
